# Generated by Django 5.2.7 on 2025-11-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_artista_creador', models.CharField(max_length=255)),
                ('nombre_comunidad', models.CharField(max_length=100, unique=True)),
                ('desc_comunidad', models.TextField(blank=True, null=True)),
                ('ruta_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('palabras_vetadas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('ruta_fichero', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('id_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='ComunidadMiembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=255)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('id_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
            ],
            options={
                'unique_together': {('id_comunidad', 'id_usuario')},
            },
        ),
        migrations.CreateModel(
            name='PersonasVetadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_miembro', models.CharField(max_length=255)),
                ('fecha_veto', models.DateTimeField(auto_now_add=True)),
                ('id_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
            ],
            options={
                'unique_together': {('id_comunidad', 'id_miembro')},
            },
        ),
        migrations.CreateModel(
            name='PublicacionMeGusta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=255)),
                ('fecha_megusta', models.DateTimeField(auto_now_add=True)),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.publicacion')),
            ],
            options={
                'unique_together': {('id_publicacion', 'id_usuario')},
            },
        ),
    ]
