# Generated by Django 5.2.8 on 2025-11-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('idArtista', models.CharField(max_length=255)),
                ('nombreComunidad', models.CharField(max_length=100, unique=True)),
                ('descComunidad', models.TextField(blank=True, null=True)),
                ('rutaImagen', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('palabrasVetadas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('rutaFichero', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('idComunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='ComunidadMiembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.CharField(max_length=255)),
                ('fechaUnion', models.DateTimeField(auto_now_add=True)),
                ('idComunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
            ],
            options={
                'unique_together': {('idComunidad', 'idUsuario')},
            },
        ),
        migrations.CreateModel(
            name='PersonasVetadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMiembro', models.CharField(max_length=255)),
                ('fechaVeto', models.DateTimeField(auto_now_add=True)),
                ('idComunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
            ],
            options={
                'unique_together': {('idComunidad', 'idMiembro')},
            },
        ),
        migrations.CreateModel(
            name='PublicacionMeGusta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.CharField(max_length=255)),
                ('fechaMegusta', models.DateTimeField(auto_now_add=True)),
                ('idPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.publicacion')),
            ],
            options={
                'unique_together': {('idPublicacion', 'idUsuario')},
            },
        ),
    ]
