# Generated by Django 5.2.8 on 2025-11-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunidad',
            old_name='id',
            new_name='idComunidad',
        ),
    ]
